{{- if and .Values.serviceAccount.create (not .Values.serviceAccount.name) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lavinmq.serviceAccountName" . | quote }}
  labels:
    {{- include "lavinmq.labels" . | nindent 4 }}
{{- end }}