name: "Push chart to ghcr.io"

on:
  push:
    paths:
      - Chart.yaml
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  
env:
  HELM_VERSION: 3.11.2
  CHARTS_SRC_DIR: "."
  TARGET_REGISTRY: ghcr.io
  TARGET_REPO: simcubeltd/lavinmq

jobs:
  release-charts:
    name: Release charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout chart sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Install Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.9.3
        with:
          setup-tools: |
            helm
            yq
          helm: "${{ env.HELM_VERSION }}"

      - name: Log into helm repo
        shell: bash
        run: |
          helm registry login ghcr.io/${{ env.TARGET_REGISTRY }}/charts -u ${{ github.actor }}  --password ${{ secrets.GITHUB_TOKEN }}
 
      - name: Package & Push Helm Charts
        shell: bash
        run: |
          CHART_VERSION=$(yq e '.version' Chart.yaml)
          helm package . --dependency-update --destination . --version "${CHART_VERSION}"
          helm push lavinmq-${CHART_VERSION}.tgz oci://${{ env.TARGET_REGISTRY }}/${{ env.TARGET_REPO }}